version: '3.7'
#
services:
  iris:
    image: containers.intersystems.com/intersystems/iris-community:2022.2.0.293.0
    init: true
    hostname: iris

    ports:
    # superserver default port 
    - "51777:1972"
    # webserver/management portal port
    - "52773:52773"

    volumes:
    - ./UserCPF:/home/irisowner/cpf
    - ./sql:/home/irisowner/sql
    - ./src:/home/irisowner/src
    - ./isc-taxi-demo/src:/home/irisowner/taxi/src
    - ./isc-taxi-demo/data:/home/irisowner/taxi/data

    environment:
    - TZ=JST-9
    #; comment out this line to disable durable sys
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
